default_roles:
  # - zsh
  - nix
  # - ufw
  # - openssh
  # - users 
  # - test

exclude_roles:
  - bootstrap

facts_op_installed: false
facts_nix_installed: false
facts_zsh_installed: false
facts_sillypoise_exists: false
facts_flubber_exists: false
