default_roles:
  # - zsh
  - nix
  # - ufw
  # - openssh
  # - users 
  # - test

exclude_roles:
  - bootstrap

facts:
  op_installed: false
  nix_installed: false
  zsh_installed: false
  sillypoise_exists: false
  flubber_exists: false
