- name: Copy bash config for host user
  ansible.builtin.copy:
    src: "bashrc"
    dest: "{{ host_user_home }}/.bashrc"
    mode: "0644"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - environment

- name: Copy custom bash config directory
  ansible.builtin.copy:
    dest: "{{ host_user_home }}/.config/"
    src: "bash"
    mode: "0644"
    directory_mode: "0755"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    force: true
  tags:
    - environment
