- name: Copy bash config for both users
  ansible.builtin.copy:
    src: "bashrc"
    dest: "{{ item.path }}/.bashrc"
    mode: "0644"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: "{{ host_user_home }}", owner: "{{ host_user }}", group: "{{ host_user }}" }
    - { path: "{{ automated_user_home }}", owner: "{{ automated_user }}", group: "{{ automated_user }}" }
  tags:
    - environment
