---
# roles/ssh/tasks/main.yml
- name: Ensure .ssh directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ host_user_home }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - ssh
    - security

- name: Copy SSH key templates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ host_user_home }}/.ssh/"
    mode: '0600'
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  with_items:
    - gh_id_ed25519.tpl
  tags:
    - ssh
    - security

- name: Inject GitHub SSH private key
  become_user: "{{ host_user }}"
  ansible.builtin.shell: "op inject -i {{ host_user_home }}/.ssh/gh_id_ed25519.tpl -o {{ host_user_home }}/.ssh/gh_id_ed25519 -f"
  register: inject_gh_private_key
  no_log: true
  tags:
    - ssh
    - security
    - secrets

- name: Ensure correct permissions on SSH files
  ansible.builtin.file:
    path: "{{ host_user_home }}/.ssh/{{ item.file }}"
    mode: "{{ item.mode }}"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  with_items:
    - { file: 'gh_id_ed25519', mode: '0600' }
    - { file: 'gh_id_ed25519.pub', mode: '0644' }
  tags:
    - ssh
    - security
