- name: Copy .zshrc for host user
  ansible.builtin.copy:
    src: "zshrc"
    dest: "{{ host_user_home }}/.zshrc"
    mode: "0644"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - environment

- name: Copy custom Zsh config directory
  ansible.builtin.copy:
    src: "zsh"
    dest: "{{ host_user_home }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    force: true
  tags:
    - environment

- name: Inject secrets into Zsh config
  become_user: "{{ host_user }}"
  ansible.builtin.shell: "op inject -i {{ host_user_home }}/.config/zsh/vars.secret.tpl -o {{ host_user_home }}/.config/zsh/vars.secret -f"
  register: inject_result
  no_log: true
  tags:
    - secrets
    - op
  changed_when: false

- name: Ensure op_token.zsh has secure permissions
  ansible.builtin.file:
    path: "{{ host_user_home }}/.config/zsh/vars.secret"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: '0600'

- name: Ensure vars.secret has secure permissions
  ansible.builtin.file:
    path: "{{ host_user_home }}/.config/zsh/vars.secret"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: '0600'
