- name: Install Zsh (Arch)
  ansible.builtin.pacman:
    name: zsh
    state: present
  register: zsh_install_arch
  when: facts_is_arch and not facts_zsh_installed
  tags:
    - system
    - packages
    - zsh

- name: Install Zsh (Ubuntu)
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
  register: zsh_install_ubuntu
  when: facts_is_ubuntu and not facts_zsh_installed
  tags:
    - system
    - packages
    - zsh

- name: Set Zsh as default shell for host user
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /bin/zsh
  become: true
  when: >-
    facts_zsh_installed or
    (zsh_install_arch is defined and zsh_install_arch is succeeded) or
    (zsh_install_ubuntu is defined and zsh_install_ubuntu is succeeded)
  tags:
    - shell
    - zsh

- name: Copy .zshrc for host user
  ansible.builtin.copy:
    src: "zshrc"
    dest: "{{ host_user_home }}/.zshrc"
    mode: "0644"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - environment

- name: Copy .psqlrc for host user
  ansible.builtin.copy:
    src: "psqlrc"
    dest: "{{ host_user_home }}/.psqlrc"
    mode: "0644"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - environment
    - zsh

- name: Copy custom Zsh config directory
  ansible.builtin.copy:
    src: "zsh"
    dest: "{{ host_user_home }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    force: true
  tags:
    - environment

- name: Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ host_user_home }}/.local/bin"
    state: directory
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: "0755"
  become: true
  become_user: "{{ host_user }}"
  tags:
    - environment
    - zsh
