---
- name: Install UFW on Arch Linux
  ansible.builtin.pacman:
    name: ufw
    state: present
  when: ansible_os_family == "Archlinux"

- name: Enable and start UFW
  ansible.builtin.systemd:
    name: ufw
    enabled: true
    state: started

- name: Set default UFW policies
  ansible.builtin.ufw:
    state: enabled
    policy: allow
    direction: outgoing
  notify: Restart UFW

- name: Block HTTP/HTTPS on all public interfaces
  ansible.builtin.ufw:
    rule: deny
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports | difference([22]) }}"  # Excludes SSH port

# Allow all traffic on the Tailscale interface
- name: Allow all traffic on Tailscale interface
  ansible.builtin.ufw:
    rule: allow
    interface_in: "{{ ufw_tailscale_interface }}"
    from_ip: "any"
  notify: Restart UFW

# Allow SSH on the public interface (to ensure access even if Tailscale is unavailable)
- name: Allow SSH on public interface
  ansible.builtin.ufw:
    rule: allow
    port: 22
    proto: tcp
  notify: Restart UFW
