---
- name: Install GitHub CLI (Ubuntu)
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
  when: facts_is_ubuntu
  tags:
    - gh
    - packages

- name: Install GitHub CLI (Arch)
  ansible.builtin.pacman:
    name: github-cli
    state: present
  when: facts_is_arch
  tags:
    - gh
    - packages

- name: Ensure gh config directory exists
  ansible.builtin.file:
    path: "{{ host_user_home }}/.config/gh"
    state: directory
    mode: '0755'
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - gh
    - config

- name: Copy gh config file
  ansible.builtin.copy:
    src: config.yml
    dest: "{{ host_user_home }}/.config/gh/config.yml"
    mode: '0644'
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - gh
    - config
