# Set Zsh as the default shell for sillypoise
- name: "Set Zsh as default shell for {{ host_user }}"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /bin/zsh
  become: true
  tags:
    - shell

- name: "Fetch {{ host_user }} passwd"
  become_user: "{{ host_user }}"
  ansible.builtin.command:
    cmd: "op read 'op://sp-dev/user/hashed'"
  register: new_password
  no_log: true

# TODO: non-idempotent
- name: "Set passwd for {{ host_user }}"
  ansible.builtin.user:
    name: sillypoise
    password: "{{ new_password.stdout }}"
  become: true
  no_log: true

# Set fact to mark that password setup is complete
- name: "Set password setup complete fact for {{ host_user }}"
  ansible.builtin.set_fact:
    facts_password_setup_complete: true
  tags:
    - shell
