# Set Zsh as the default shell for sillypoise
- name: "Set Zsh as default shell for {{ host_user }}"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /bin/zsh
  become: true
  tags:
    - shell

- name: Ensure /bin/zsh symlink points to Nix Zsh binary
  ansible.builtin.file:
    src: "/home/{{ host_user }}/.nix-profile/bin/zsh"  # Adjust if the Nix-installed Zsh is in a different location
    dest: "/bin/zsh"
    state: link
  tags:
    - shell
    - environment
    - zsh

- name: "Fetch {{ host_user }} passwd"
  become_user: "{{ host_user }}"
  ansible.builtin.command:
    cmd: "op read 'op://sp-dev/user/hashed'"
  register: new_password
  no_log: true

# TODO: non-idempotent
- name: "Set passwd for {{ host_user }}"
  ansible.builtin.user:
    name: "{{ host_user }}"
    password: "{{ new_password.stdout }}"
  become: true
  no_log: true
