- name: Source Nix environment
  ansible.builtin.shell: |
    . /etc/profile.d/nix.sh
  args:
    executable: /bin/bash
  changed_when: false
  tags:
    - nix
    - environment

- name: Verify Nix is available
  ansible.builtin.command: which nix
  register: nix_check
  failed_when: nix_check.rc != 0
  tags:
    - nix
    - check
  ignore_errors: false

# - name: system setup | nix | add home-manager channel
#   shell: nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.05.tar.gz home-manager
#   tags:
#     - nix
#     - home-manager
#
# - name: system setup | nix | update nix channels
#   shell: nix-channel --update
#   tags:
#     - nix
#     - home-manager
#
# - name: system setup | nix | install home-manager into profile
#   shell: nix-env -iA nixpkgs.home-manager
#   tags:
#     - nix
#     - home-manager
#
# - name: system setup | nix | create .config/nixpkgs directory for home manager config
#   file:
#     path: "{{ ansible_user_dir }}/.config/home-manager"
#     state: directory
#     owner: "{{ host_user }}"
#     group: "{{ host_user }}"
#     # permissions so home-manager can write to it
#     mode: '0755'
#   tags:
#     - nix
#     - home-manager
#
# - name: system setup | nix | copy home-manager configuration file
#   copy:
#     src: "{{ host_user }}/home.nix"
#     dest: "{{ ansible_user_dir }}/.config/home-manager/home.nix"
#     owner: "{{ host_user }}"
#     group: "{{ host_user }}"
#     mode: '0644'
#   tags:
#     - nix
#     - home-manager
#     - packages
#
# - name: system setup | nix | install packages via home-manager
#   shell: "sudo -i -u {{ host_user }} home-manager switch -f /home/sillypoise/.config/home-manager/home.nix"
#   tags:
#     - nix
#     - home-manager
#     - packages
#
# - name: system setup | nix | update nix channels
#   shell: nix-channel --update
#   tags:
#     - nix
#     - home-manager
#     - update
#
# - name: system setup | nix | update home-manager packages
#   shell: "sudo -i -u {{ host_user }} home-manager switch -b backup"
#   tags:
#     - nix
#     - home-manager
#     - packages
#     - update
