---
- name: Debug | Show all tools facts
  ansible.builtin.debug:
    var: facts.tools
  tags:
    - always

# Register Current User
- name: Register Current User if Undefined
  ansible.builtin.set_fact:
    host_user: "{{ ansible_env['USER'] }}"
  when: host_user is not defined
  tags:
    - always

# Detect 1Password CLI installation if not already marked as installed
- name: Detect 1Password CLI
  ansible.builtin.command:
    cmd: which op
  changed_when: false
  failed_when: false
  register: op_detection
  when: not facts.tools.op_installed  # Only check if `op_installed` is false
  tags:
    - always

- name: Set 1Password Installed Status
  ansible.builtin.set_fact:
    facts:
      tools:
        op_installed: "{{ op_detection.rc == 0 }}"
  when: op_detection is defined
  tags:
    - always

# Detect Nix installation if not already marked as installed
- name: Detect Nix Installation
  ansible.builtin.command:
    cmd: which nix
  changed_when: false
  failed_when: false
  register: nix_detection
  when: not facts.tools.nix_installed
  tags:
    - always

- name: Set Nix Installed Status
  ansible.builtin.set_fact:
    facts:
      tools:
        nix_installed: "{{ nix_detection.rc == 0 }}"
  when: nix_detection is defined
  tags:
    - always

# Detect Zsh installation if not already marked as installed
- name: Detect Zsh Installation
  ansible.builtin.command:
    cmd: which zsh
  changed_when: false
  failed_when: false
  register: zsh_detection
  when: not facts.tools.zsh_installed
  tags:
    - always

- name: Set Zsh Installed Status
  ansible.builtin.set_fact:
    facts:
      tools:
        zsh_installed: "{{ zsh_detection.rc == 0 }}"
  when: zsh_detection is defined
  tags:
    - always

# Check for the existence of the `sillypoise` user if not already marked as installed
- name: Detect sillypoise User
  ansible.builtin.command:
    cmd: id -u sillypoise
  changed_when: false
  failed_when: false
  register: sillypoise_user_detection
  when: not facts.users.sillypoise_exists
  tags:
    - always

- name: Set sillypoise User Existence Status
  ansible.builtin.set_fact:
    facts:
      users:
        sillypoise_exists: "{{ sillypoise_user_detection.rc == 0 }}"
  when: sillypoise_user_detection is defined
  tags:
    - always

# Check for the existence of the `flubber` user if not already marked as installed
- name: Detect flubber User
  ansible.builtin.command:
    cmd: id -u flubber
  changed_when: false
  failed_when: false
  register: flubber_user_detection
  when: not facts.users.flubber_exists
  tags:
    - always

- name: Set flubber User Existence Status
  ansible.builtin.set_fact:
    facts:
      users:
        flubber_exists: "{{ flubber_user_detection.rc == 0 }}"
  when: flubber_user_detection is defined
  tags:
    - always
