---
- name: Clone private Neovim config repo
  ansible.builtin.git:
    repo: "git@github.com:{{ gh_user }}/nvim-config.git"
    dest: "{{ host_user_home }}/.config/nvim"
    version: main  # or specify your desired branch/tag
  become_user: "{{ host_user }}"
  when: facts_gh_authed
  tags:
    - neovim
    - config
