---
- name: Clone public Neovim config repo
  ansible.builtin.git:
    repo: "https://github.com/sillypoise/sp-nvim.git"
    dest: "{{ host_user_home }}/.config/nvim"
    clone: yes
    update: yes
  become_user: "{{ host_user }}"
  changed_when: not ansible_check_mode
  tags:
    - neovim
    - config
